import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import Image from "next/image";
import { Box } from "@chakra-ui/layout";
import MainLayout from "../components/MainLayout";
import TextBlock from "../components/TextBlock";
import union from "../images/cupid.png";
import Sections from "../components/Sections";
import Falling from "../components/Falling/Falling";
import "../images/heart.svg";

const Backdrop = () => {
  return (
    <div
      style={{
        overflow: "hidden",
        height: "inherit",
        width: "100%",
        position: "absolute",
        top: 0,
        left: 0,
      }}
    >
      {Array(20)
        .fill(0)
        .map((_, index) => (
          <Falling key={index} delay={600 * index}>
            ♥
          </Falling>
        ))}
    </div>
  );
};

const sections = [
  {
    id: "1",
    label: "Label 1",
    content: (
      <Box height={500} id="1">
        1
      </Box>
    ),
  },
  {
    id: "2",
    label: "Label 2",
    content: (
      <Box height={500} id="2">
        2
      </Box>
    ),
  },
];

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <MainLayout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        scrollBehavior="smooth"
        overflowY="scroll"
        height="100vh"
        backgroundColor="gray.50"
      >
        <Box
          backgroundColor="white"
          position="relative"
          py={10}
          minH="2xl"
          display="flex"
          alignItems="center"
          justifyContent="center"
          flexDir="column"
        >
          <Image src={union} width={70} height={70} alt="Rings" />
          <TextBlock
            title="Welcome to our big fat Croatian wedding"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, quaerat?"
          />
          <Box height="100%">
            <Backdrop />
          </Box>
        </Box>
        <Sections sections={sections} />
      </Box>
    </MainLayout>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}
