import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import { Box } from "@chakra-ui/layout";
import MainLayout from "../components/MainLayout";
import TextBlock from "../components/TextBlock";
import cupid from "../images/cupid.png";
import hero from "../images/hero.jpeg";
import Heart from "../images/other_heart_full.svg";
import Sections from "../components/Sections";
import Falling from "../components/Falling/Falling";
import { useEffect, useRef } from "react";

const Backdrop = () => {
  return (
    <div
      style={{
        overflow: "hidden",
        height: "inherit",
        width: "100%",
        position: "absolute",
        top: 0,
        left: 0,
      }}
    >
      {Array(20)
        .fill(0)
        .map((_, index) => (
          <Falling key={index} delay={600 * index}>
            ♥
          </Falling>
        ))}
    </div>
  );
};

const sections = [
  {
    id: "1",
    label: "Label 1",
    imgSrc: cupid,
    contained: true,
    content: (
      <Box height={500} id="1">
        1
      </Box>
    ),
  },
  {
    id: "2",
    label: "Label 2",
    imgSrc: cupid,
    contained: false,
    content: (
      <Box height={500} id="2">
        2
      </Box>
    ),
  },
];

export default function Home() {
  const ref = useRef();
  const { t } = useTranslation("common");

  useEffect(() => {
    const element = ref.current;
    if (!element) return;
    const handler = () => {
      element.querySelector("path").classList.add("fill");
    };
    element.addEventListener("animationend", handler);
    return () => {
      element.removeEventListener("animationend", handler);
    };
  }, []);

  return (
    <MainLayout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box overflowY="scroll" height="100vh" backgroundColor="gray.50">
        <Box
          backgroundColor="white"
          position="relative"
          py={10}
          minH="2xl"
          display="flex"
          alignItems="center"
          justifyContent="center"
          flexDir="column"
        >
          <div ref={ref} className="draw">
            <Heart width="100%" />
          </div>
          {/* <Box className="hero-heart">
            <Image src={hero} layout="fill" alt="Hero" />,
          </Box> */}
          {/* <Image src={union} width={70} height={70} alt="Rings" /> */}
          <TextBlock
            title="Welcome to our big fat Croatian wedding"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, quaerat?"
          />
          <Box height="100%">
            <Backdrop />
          </Box>
        </Box>
        <Sections sections={sections} />
      </Box>
    </MainLayout>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}
